server:
  port: 8081

spring:
  application:
    name: electricity-billing-api
  datasource:
    url: jdbc:mysql://localhost:3306/electricity-billing-system
    username: group07
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
    baseline-on-migrate: true

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
